stages: 
  - deploy

serverPull:
  only:
    refs:
      - master
  stage: deploy
  image: ubuntu
  before_script:
    - which ssh || apt update && apt install -y ca-certificates &&  apt install -y ssh
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config 
    - chmod 400 $SSH_KEY
  script: 
    - ssh -i $SSH_KEY $SSH_USER@$SSH_HOSTNAME "cd $CI_PROJECT_NAME &&
      git reset --hard && git pull &&
      npm i --no-save && npm run pm2:restart"